export const INDIA_COUNTRY_CODE = '+91';

export const EVENT_TYPES = {
  CUSTOM: 'CUSTOM',
  SIGHTSEEING: 'SIGHTSEEING',
  REFUELING: 'REFUELING',
  COFFEE_BREAK: 'COFFEE_BREAK',
  REPAIR: 'REPAIR',
  GOT_LOST: 'GOT_LOST',
  PULL_OVER: 'PULL_OVER',
};
